### ISSUE TITLE
Need some help with creating theme(git), thanks

### ISSUE THREAD

**Issue by chinanoahli** [BinaryMuse/oh-my-zsh#2]
I am creating a theme. I want to put the git information in `RPROMPT`. I read `xiong-chiamiov-plus.zsh-theme`, and I found it just used `$(git_prompt_info)` to show the stats of git. But when I put it in my theme, it doesn't work.

This is my code:

```
CURRENTUSER=`whoami`
if [ "$CURRENTUSER" = "root" ]; then USERCOLOR="red"; else USERCOLOR="cyan"; fi

PROMPT="┌\
%{$fg[$USERCOLOR]%}%{$bg[black]%} [%n> %{$reset_color%}\
%{$fg[yellow]%}%{$bg[black]%}[%m> %{$reset_color%}\
%{$fg[black]%}%{$bg[blue]%}[%~> %{$reset_color%}\
%{$fg[white]%} %#%{$reset_color%}
└\
 %(?,%{$fg[green]%}%{$bg[black]%}[%?>%{$reset_color%},%{$fg[red]%}%{$bg[black]%}[%?>%{$reset_color%}) \
"

RPROMPT="### I want to put the git info here###    %{$bg[white]%} %{$fg[black]%}<! %!%{$reset_color%}%{$fg[black]%}%{$bg[blue]%} <%*%{$reset_color%}"

PS2="%{$fg[yellow]%}> %!%{$reset_color%}"
```

**Comment by chinanoahli** [comment]
When I update zsh on my OS X, I found if you use `su` to change your login as root, the `$USER` is NOT `root`, it still the name of that you used it to `su`, but if you run `whoami` after `su`, it will return `root`, so I decided use this to find what user is be using.

**Comment by BinaryMuse** [comment]
@chinanoahli This is not the official oh-my-zsh repo; that's at robbyrussell/oh-my-zsh. This is just a personal fork.

**Comment by chinanoahli** [comment]
Oh, Sorry, I didn't notice!
